@name = jack
@email = jack@gmail.com
@privateKey = shfgeduf

@senha = 12345233
@acessType = fornecedor

@balance = 5
@PublicKey =  xxx
### Listar usuários
GET http://localhost:3000/user

### Obter usuário
GET http://localhost:3000/user/chico@gmail.com/123456



### Criar usuário
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "{{name}}",
    "email": "{{email}}",
    "privateKey": "{{privateKey}}",
    "senha": "{{senha}}",
    "acessType": "{{acessType}}",
    "balance":"{{balance}}",
    "PublicKey":"{{PublicKey}}"
}

### Atualizar usuário
PATCH http://localhost:3000/user/
Content-Type: application/json

{"balance":"{{balance}}"}


### Deletar usuário
DELETE http://localhost:3000/user/user_ips2IWwm6FPEOV3BNzbvS